export const SHOW_PRODUCTS = 'SHOW_PRODUCTS';
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const CHANGE_QUANTITY = 'CHANGE_QUANTITY';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const SET_SHIPPING_COST = 'SET_SHIPPING_COST';
